//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.312.
// 

namespace UPSXml
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RatingServiceSelectionResponse
    {

        private ResponseType responseField;

        private RatedShipmentType[] ratedShipmentField;

        /// <remarks/>
        public ResponseType Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RatedShipment")]
        public RatedShipmentType[] RatedShipment
        {
            get
            {
                return this.ratedShipmentField;
            }
            set
            {
                this.ratedShipmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseType
    {

        private TransactionReferenceType transactionReferenceField;

        private string responseStatusCodeField;

        private string responseStatusDescriptionField;

        private ErrorType[] errorField;

        /// <remarks/>
        public TransactionReferenceType TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }

        /// <remarks/>
        public string ResponseStatusCode
        {
            get
            {
                return this.responseStatusCodeField;
            }
            set
            {
                this.responseStatusCodeField = value;
            }
        }

        /// <remarks/>
        public string ResponseStatusDescription
        {
            get
            {
                return this.responseStatusDescriptionField;
            }
            set
            {
                this.responseStatusDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error")]
        public ErrorType[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NetSummaryChargesType
    {

        private ChargesType grandTotalField;

        /// <remarks/>
        public ChargesType GrandTotal
        {
            get
            {
                return this.grandTotalField;
            }
            set
            {
                this.grandTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargesType
    {

        private string currencyCodeField;

        private string monetaryValueField;

        /// <remarks/>
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }

        /// <remarks/>
        public string MonetaryValue
        {
            get
            {
                return this.monetaryValueField;
            }
            set
            {
                this.monetaryValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NegotiatedRatesType
    {

        private NetSummaryChargesType netSummaryChargesField;

        /// <remarks/>
        public NetSummaryChargesType NetSummaryCharges
        {
            get
            {
                return this.netSummaryChargesField;
            }
            set
            {
                this.netSummaryChargesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RatedPackageType
    {

        private ChargesType transportationChargesField;

        private ChargesType serviceOptionsChargesField;

        private ChargesType totalChargesField;

        private string weightField;

        private WeightType billingWeightField;

        /// <remarks/>
        public ChargesType TransportationCharges
        {
            get
            {
                return this.transportationChargesField;
            }
            set
            {
                this.transportationChargesField = value;
            }
        }

        /// <remarks/>
        public ChargesType ServiceOptionsCharges
        {
            get
            {
                return this.serviceOptionsChargesField;
            }
            set
            {
                this.serviceOptionsChargesField = value;
            }
        }

        /// <remarks/>
        public ChargesType TotalCharges
        {
            get
            {
                return this.totalChargesField;
            }
            set
            {
                this.totalChargesField = value;
            }
        }

        /// <remarks/>
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public WeightType BillingWeight
        {
            get
            {
                return this.billingWeightField;
            }
            set
            {
                this.billingWeightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RatedShipmentType
    {

        private CodeDescriptionType serviceField;

        private string[] ratedShipmentWarningField;

        private WeightType billingWeightField;

        private ChargesType transportationChargesField;

        private ChargesType serviceOptionsChargesField;

        private ChargesType totalChargesField;

        private string guaranteedDaysToDeliveryField;

        private string scheduledDeliveryTimeField;

        private RatedPackageType[] ratedPackageField;

        private NegotiatedRatesType negotiatedRatesField;

        /// <remarks/>
        public CodeDescriptionType Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RatedShipmentWarning")]
        public string[] RatedShipmentWarning
        {
            get
            {
                return this.ratedShipmentWarningField;
            }
            set
            {
                this.ratedShipmentWarningField = value;
            }
        }

        /// <remarks/>
        public WeightType BillingWeight
        {
            get
            {
                return this.billingWeightField;
            }
            set
            {
                this.billingWeightField = value;
            }
        }

        /// <remarks/>
        public ChargesType TransportationCharges
        {
            get
            {
                return this.transportationChargesField;
            }
            set
            {
                this.transportationChargesField = value;
            }
        }

        /// <remarks/>
        public ChargesType ServiceOptionsCharges
        {
            get
            {
                return this.serviceOptionsChargesField;
            }
            set
            {
                this.serviceOptionsChargesField = value;
            }
        }

        /// <remarks/>
        public ChargesType TotalCharges
        {
            get
            {
                return this.totalChargesField;
            }
            set
            {
                this.totalChargesField = value;
            }
        }

        /// <remarks/>
        public string GuaranteedDaysToDelivery
        {
            get
            {
                return this.guaranteedDaysToDeliveryField;
            }
            set
            {
                this.guaranteedDaysToDeliveryField = value;
            }
        }

        /// <remarks/>
        public string ScheduledDeliveryTime
        {
            get
            {
                return this.scheduledDeliveryTimeField;
            }
            set
            {
                this.scheduledDeliveryTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RatedPackage")]
        public RatedPackageType[] RatedPackage
        {
            get
            {
                return this.ratedPackageField;
            }
            set
            {
                this.ratedPackageField = value;
            }
        }

        /// <remarks/>
        public NegotiatedRatesType NegotiatedRates
        {
            get
            {
                return this.negotiatedRatesField;
            }
            set
            {
                this.negotiatedRatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorLocationType
    {

        private string errorLocationElementNameField;

        private string errorLocationElementReferenceField;

        private string errorLocationAttributeNameField;

        /// <remarks/>
        public string ErrorLocationElementName
        {
            get
            {
                return this.errorLocationElementNameField;
            }
            set
            {
                this.errorLocationElementNameField = value;
            }
        }

        /// <remarks/>
        public string ErrorLocationElementReference
        {
            get
            {
                return this.errorLocationElementReferenceField;
            }
            set
            {
                this.errorLocationElementReferenceField = value;
            }
        }

        /// <remarks/>
        public string ErrorLocationAttributeName
        {
            get
            {
                return this.errorLocationAttributeNameField;
            }
            set
            {
                this.errorLocationAttributeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorType
    {

        private string errorSeverityField;

        private string errorCodeField;

        private string errorDescriptionField;

        private string minimumRetrySecondsField;

        private ErrorLocationType[] errorLocationField;

        private string[] errorDigestField;

        /// <remarks/>
        public string ErrorSeverity
        {
            get
            {
                return this.errorSeverityField;
            }
            set
            {
                this.errorSeverityField = value;
            }
        }

        /// <remarks/>
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }

        /// <remarks/>
        public string MinimumRetrySeconds
        {
            get
            {
                return this.minimumRetrySecondsField;
            }
            set
            {
                this.minimumRetrySecondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorLocation")]
        public ErrorLocationType[] ErrorLocation
        {
            get
            {
                return this.errorLocationField;
            }
            set
            {
                this.errorLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorDigest")]
        public string[] ErrorDigest
        {
            get
            {
                return this.errorDigestField;
            }
            set
            {
                this.errorDigestField = value;
            }
        }
    }
}