//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.312.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RatingServiceSelectionRequest {
    
    private RequestType requestField;
    
    private CodeType pickupTypeField;
    
    private CodeType customerClassificationField;
    
    private ShipmentType shipmentField;
    
    /// <remarks/>
    public RequestType Request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    public CodeType PickupType {
        get {
            return this.pickupTypeField;
        }
        set {
            this.pickupTypeField = value;
        }
    }
    
    /// <remarks/>
    public CodeType CustomerClassification {
        get {
            return this.customerClassificationField;
        }
        set {
            this.customerClassificationField = value;
        }
    }
    
    /// <remarks/>
    public ShipmentType Shipment {
        get {
            return this.shipmentField;
        }
        set {
            this.shipmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequestType {
    
    private string requestActionField;
    
    private string requestOptionField;
    
    private TransactionReferenceType transactionReferenceField;
    
    /// <remarks/>
    public string RequestAction {
        get {
            return this.requestActionField;
        }
        set {
            this.requestActionField = value;
        }
    }
    
    /// <remarks/>
    public string RequestOption {
        get {
            return this.requestOptionField;
        }
        set {
            this.requestOptionField = value;
        }
    }
    
    /// <remarks/>
    public TransactionReferenceType TransactionReference {
        get {
            return this.transactionReferenceField;
        }
        set {
            this.transactionReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TransactionReferenceType {
    
    private string customerContextField;
    
    private string xpciVersionField;
    
    private string toolVersionField;
    
    /// <remarks/>
    public string CustomerContext {
        get {
            return this.customerContextField;
        }
        set {
            this.customerContextField = value;
        }
    }
    
    /// <remarks/>
    public string XpciVersion {
        get {
            return this.xpciVersionField;
        }
        set {
            this.xpciVersionField = value;
        }
    }
    
    /// <remarks/>
    public string ToolVersion {
        get {
            return this.toolVersionField;
        }
        set {
            this.toolVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RateInformationType {
    
    private string negotiatedRatesIndicatorField;
    
    /// <remarks/>
    public string NegotiatedRatesIndicator {
        get {
            return this.negotiatedRatesIndicatorField;
        }
        set {
            this.negotiatedRatesIndicatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ScheduleType {
    
    private string pickupDayField;
    
    private string methodField;
    
    /// <remarks/>
    public string PickupDay {
        get {
            return this.pickupDayField;
        }
        set {
            this.pickupDayField = value;
        }
    }
    
    /// <remarks/>
    public string Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OnCallAirType {
    
    private ScheduleType scheduleField;
    
    /// <remarks/>
    public ScheduleType Schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShipmentServiceOptionsType {
    
    private string saturdayPickupField;
    
    private string saturdayDeliveryField;
    
    private OnCallAirType onCallAirField;
    
    private CODType cODField;
    
    private string returnOfDocumentIndicatorField;
    
    private DeliveryConfirmationType deliveryConfirmationField;
    
    /// <remarks/>
    public string SaturdayPickup {
        get {
            return this.saturdayPickupField;
        }
        set {
            this.saturdayPickupField = value;
        }
    }
    
    /// <remarks/>
    public string SaturdayDelivery {
        get {
            return this.saturdayDeliveryField;
        }
        set {
            this.saturdayDeliveryField = value;
        }
    }
    
    /// <remarks/>
    public OnCallAirType OnCallAir {
        get {
            return this.onCallAirField;
        }
        set {
            this.onCallAirField = value;
        }
    }
    
    /// <remarks/>
    public CODType COD {
        get {
            return this.cODField;
        }
        set {
            this.cODField = value;
        }
    }
    
    /// <remarks/>
    public string ReturnOfDocumentIndicator {
        get {
            return this.returnOfDocumentIndicatorField;
        }
        set {
            this.returnOfDocumentIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public DeliveryConfirmationType DeliveryConfirmation {
        get {
            return this.deliveryConfirmationField;
        }
        set {
            this.deliveryConfirmationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CODType {
    
    private string cODFundsCodeField;
    
    private AmountType cODAmountField;
    
    /// <remarks/>
    public string CODFundsCode {
        get {
            return this.cODFundsCodeField;
        }
        set {
            this.cODFundsCodeField = value;
        }
    }
    
    /// <remarks/>
    public AmountType CODAmount {
        get {
            return this.cODAmountField;
        }
        set {
            this.cODAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AmountType {
    
    private string currencyCodeField;
    
    private string monetaryValueField;
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string MonetaryValue {
        get {
            return this.monetaryValueField;
        }
        set {
            this.monetaryValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeliveryConfirmationType {
    
    private string dCISTypeField;
    
    /// <remarks/>
    public string DCISType {
        get {
            return this.dCISTypeField;
        }
        set {
            this.dCISTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StructuredPhoneNumberType {
    
    private string phoneCountryCodeField;
    
    private string phoneDialPlanNumberField;
    
    private string phoneLineNumberField;
    
    private string phoneExtensionField;
    
    /// <remarks/>
    public string PhoneCountryCode {
        get {
            return this.phoneCountryCodeField;
        }
        set {
            this.phoneCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneDialPlanNumber {
        get {
            return this.phoneDialPlanNumberField;
        }
        set {
            this.phoneDialPlanNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneLineNumber {
        get {
            return this.phoneLineNumberField;
        }
        set {
            this.phoneLineNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneExtension {
        get {
            return this.phoneExtensionField;
        }
        set {
            this.phoneExtensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PhoneNumberType {
    
    private StructuredPhoneNumberType structuredPhoneNumberField;
    
    /// <remarks/>
    public StructuredPhoneNumberType StructuredPhoneNumber {
        get {
            return this.structuredPhoneNumberField;
        }
        set {
            this.structuredPhoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VerbalConfirmationType {
    
    private string nameField;
    
    private PhoneNumberType phoneNumberField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public PhoneNumberType PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsuredValueType {
    
    private string currencyCodeField;
    
    private string monetaryValueField;
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string MonetaryValue {
        get {
            return this.monetaryValueField;
        }
        set {
            this.monetaryValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PackageServiceOptionsType {
    
    private InsuredValueType insuredValueField;
    
    private CODType cODField;
    
    private DeliveryConfirmationType deliveryConfirmationField;
    
    private VerbalConfirmationType verbalConfirmationField;
    
    /// <remarks/>
    public InsuredValueType InsuredValue {
        get {
            return this.insuredValueField;
        }
        set {
            this.insuredValueField = value;
        }
    }
    
    /// <remarks/>
    public CODType COD {
        get {
            return this.cODField;
        }
        set {
            this.cODField = value;
        }
    }
    
    /// <remarks/>
    public DeliveryConfirmationType DeliveryConfirmation {
        get {
            return this.deliveryConfirmationField;
        }
        set {
            this.deliveryConfirmationField = value;
        }
    }
    
    /// <remarks/>
    public VerbalConfirmationType VerbalConfirmation {
        get {
            return this.verbalConfirmationField;
        }
        set {
            this.verbalConfirmationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WeightType {
    
    private UnitOfMeasurementType unitOfMeasurementField;
    
    private string weightField;
    
    /// <remarks/>
    public UnitOfMeasurementType UnitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
    
    /// <remarks/>
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UnitOfMeasurementType {
    
    private string codeField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DimensionsType {
    
    private UnitOfMeasurementType unitOfMeasurementField;
    
    private string lengthField;
    
    private string widthField;
    
    private string heightField;
    
    /// <remarks/>
    public UnitOfMeasurementType UnitOfMeasurement {
        get {
            return this.unitOfMeasurementField;
        }
        set {
            this.unitOfMeasurementField = value;
        }
    }
    
    /// <remarks/>
    public string Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PackageType {
    
    private CodeDescriptionType packagingTypeField;
    
    private DimensionsType dimensionsField;
    
    private WeightType packageWeightField;
    
    private string oversizePackageField;
    
    private string largePackageIndicatorField;
    
    private PackageServiceOptionsType packageServiceOptionsField;
    
    private string additionalHandlingField;
    
    /// <remarks/>
    public CodeDescriptionType PackagingType {
        get {
            return this.packagingTypeField;
        }
        set {
            this.packagingTypeField = value;
        }
    }
    
    /// <remarks/>
    public DimensionsType Dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
    
    /// <remarks/>
    public WeightType PackageWeight {
        get {
            return this.packageWeightField;
        }
        set {
            this.packageWeightField = value;
        }
    }
    
    /// <remarks/>
    public string OversizePackage {
        get {
            return this.oversizePackageField;
        }
        set {
            this.oversizePackageField = value;
        }
    }
    
    /// <remarks/>
    public string LargePackageIndicator {
        get {
            return this.largePackageIndicatorField;
        }
        set {
            this.largePackageIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public PackageServiceOptionsType PackageServiceOptions {
        get {
            return this.packageServiceOptionsField;
        }
        set {
            this.packageServiceOptionsField = value;
        }
    }
    
    /// <remarks/>
    public string AdditionalHandling {
        get {
            return this.additionalHandlingField;
        }
        set {
            this.additionalHandlingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CodeDescriptionType {
    
    private string codeField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShipFromType {
    
    private string companyNameField;
    
    private AddressType addressField;
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddressType {
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string addressLine3Field;
    
    private string cityField;
    
    private string stateProvinceCodeField;
    
    private string postalCodeField;
    
    private string countryCodeField;
    
    private string residentialAddressIndicatorField;
    
    /// <remarks/>
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string StateProvinceCode {
        get {
            return this.stateProvinceCodeField;
        }
        set {
            this.stateProvinceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ResidentialAddressIndicator {
        get {
            return this.residentialAddressIndicatorField;
        }
        set {
            this.residentialAddressIndicatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShipToType {
    
    private string companyNameField;
    
    private AddressType addressField;
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShipperType {
    
    private string nameField;
    
    private string shipperNumberField;
    
    private AddressType addressField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string ShipperNumber {
        get {
            return this.shipperNumberField;
        }
        set {
            this.shipperNumberField = value;
        }
    }
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ShipmentType {
    
    private ShipperType shipperField;
    
    private ShipToType shipToField;
    
    private ShipFromType shipFromField;
    
    private CodeDescriptionType serviceField;
    
    private string documentsOnlyField;
    
    private PackageType[] packageField;
    
    private ShipmentServiceOptionsType shipmentServiceOptionsField;
    
    private RateInformationType rateInformationField;
    
    /// <remarks/>
    public ShipperType Shipper {
        get {
            return this.shipperField;
        }
        set {
            this.shipperField = value;
        }
    }
    
    /// <remarks/>
    public ShipToType ShipTo {
        get {
            return this.shipToField;
        }
        set {
            this.shipToField = value;
        }
    }
    
    /// <remarks/>
    public ShipFromType ShipFrom {
        get {
            return this.shipFromField;
        }
        set {
            this.shipFromField = value;
        }
    }
    
    /// <remarks/>
    public CodeDescriptionType Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentsOnly {
        get {
            return this.documentsOnlyField;
        }
        set {
            this.documentsOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Package")]
    public PackageType[] Package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
    
    /// <remarks/>
    public ShipmentServiceOptionsType ShipmentServiceOptions {
        get {
            return this.shipmentServiceOptionsField;
        }
        set {
            this.shipmentServiceOptionsField = value;
        }
    }
    
    /// <remarks/>
    public RateInformationType RateInformation {
        get {
            return this.rateInformationField;
        }
        set {
            this.rateInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.312")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CodeType {
    
    private string codeField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}
